### ISSUE TITLE
enableExclusiveNfc() and disableExclusiveNfc() not returning what is expected when NFC is unavailable

### ISSUE THREAD

**Issue by Franzaine** [fidesmo/nordpol#26]
Both [enableExclusiveNfc()](https://github.com/fidesmo/nordpol/blob/master/android/src/main/java/nordpol/TagDispatcher.java#L43) and [disableExclusiveNfc()](https://github.com/fidesmo/nordpol/blob/master/android/src/main/java/nordpol/TagDispatcher.java#L70) are expected to return false when NFC is not available on the device (it is put like this: "@ returns true if NFC was available and false if no NFC is available on device.") 

It should be clarified if this means that NFC is disabled or simply not physically available on the device. From the language used and the very existence of OnNfcDisabledListener I expect that the intended return value is false if, and ONLY if, NFC is actually not physically available on the device. If so [this line](https://github.com/fidesmo/nordpol/blob/master/android/src/main/java/nordpol/TagDispatcher.java#L57) has to be changed to ```return true;```

**Comment by Franzaine** [comment]
Although, ```enableExclusiveNfc()``` returning `true` when it has not enabled exclusive NFC might be illogical. The best solution might be to throw an exception?

**Comment by Franzaine** [comment]
@adriaan-telcred @petter-fidesmo @miguelcardo do you guys have any thoughts about this? It is not really functional as of now because:
If the device has NFC but it is disabled and OnNfcDisabledListener is implemented:
Both the OnNfcDisabledListener listener will be called and the methods enableExclusiveNfc and disableExclusiveNfc will return false.

This basically makes either the listener or the return values unusable.

**Comment by adriaan-telcred** [comment]
Unfortunately I can't dig deep into this right now.

I agree that the return values should provide all necessary info. Perhaps returning an enum would make more sense (e.g. NFC_NOT_PRESENT, NFC_DISABLED, NFC_ENABLED) than a boolean?

It is debatable whether an exception should be thrown if NFC is not available on the device. But an exception should not be thrown for the general failure case (unable to get exclusive NFC for whatever reason) because that does not allow the caller to handle the situation appropriately.

**Comment by petter-fidesmo** [comment]
:+1: on the enum solution. I think the basic behaviour is still correct, that it should only return success if NFC was really activated.

**Comment by petter-fidesmo** [comment]
@Franzaine Maybe you can also provide your use case. I am guessing that you want to show the end user a message if the phone does not at all have NFC, and you want to do it directly when the enableNfc... returns?

**Comment by Franzaine** [comment]
@petter-fidesmo yes. That is exactly right. As of now not having NFC at all on the device would fire both, and that sucks.

**Comment by Franzaine** [comment]
Solved by #27
