### ISSUE TITLE
Use builder pattern for TagDispatcher

### ISSUE THREAD

**Issue by slomo** [fidesmo/nordpol#54]
Currently the code to create a new `TagDispatcher` might look like this

```
dispatcher = TagDispatcher.get(this, tagArbiter, true, true, false, true, false, true);
``` 

Which is confusing. Maybe the builder pattern could improve the api here.

**Comment by petter-fidesmo** [comment]
@slomo Totally.

**Comment by dschuermann** [comment]
:+1:
