### ISSUE TITLE
Documentation build issues with XML tags in NfcGuideView

### ISSUE THREAD

**Issue by Franzaine** [fidesmo/nordpol#59]
This tag does not seem to be allowed in the documentation code: https://github.com/fidesmo/nordpol/blob/master/android/src/main/java/nordpol/ui/NfcGuideView.java#L26
It gives the following error:
[error] C:\Users\Theo\GitHub\nordpol\android\src\main\java\nordpol\ui\NfcGuideView.java:26: error: malformed HTML
[error]  * <nordpol.android.NfcGuideView
[error]    ^
[error] C:\Users\Theo\GitHub\nordpol\android\src\main\java\nordpol\ui\NfcGuideView.java:29: error: bad use of '>'
[error]  *     android:layout_height="wrap_content"/>
[error]                                             ^

This is easily amended by removing those lines, but then the documentation is sub-optimal..

**Comment by petter-fidesmo** [comment]
@Franzaine You need to use the javadoc code escape, sort of like here: http://stackoverflow.com/questions/541920/multiple-line-code-example-in-javadoc-comment
