### ISSUE TITLE
Set NfcGuideView: Set nfc_device programmatically

### ISSUE THREAD

**Issue by dschuermann** [fidesmo/nordpol#65]
It would be great if we could set ``nfc_device`` of ``NfcGuideView`` programmatically. Currently, this is only possible in XML.

**Comment by Franzaine** [comment]
Agree! We're open for any PR regarding this 😃 Would be great to be able to change the shown device depending on which is in use :)

**Comment by Franzaine** [comment]
This is addressed and released with version 0.1.21: https://github.com/fidesmo/nordpol/tree/v0.1.21
