### ISSUE TITLE
shipping 4MB of svg asset files

### ISSUE THREAD

**Issue by Valodim** [fidesmo/nordpol#70]
I looked into why OpenKeychain got so large over the last year today, and found that nordpol ships a whoopin' 4MB of svg assets, located in https://github.com/fidesmo/nordpol/tree/master/android/src/main/assets. I think those assets themselves aren't even used anywhere since there are rendered png counterparts in the drawable resources?

Either way those files bloat the library waay too much, please look into getting rid of them :)

(ping for reference, @dschuermann)

**Comment by Franzaine** [comment]
A fix for this was released in [Version 0.1.22](https://github.com/fidesmo/nordpol/releases/tag/v0.1.22)

**Comment by Valodim** [comment]
Thanks!

 - V

(sent from K-9 Mail)
